name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  maven:
    name: Maven
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "8"
          cache: maven

      - name: Build & Test
        run: mvn -B verify
