name: CI

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  maven:
    name: Maven
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Build & Test
        run: mvn -B verify
